new_names <- c("Subject", "Activity",                            
"Time_Body_Accel_Mean_X","Time_Body_Accel_Mean_Y",                   
"Time_Body_Accel_Mean_Z","Time_Body_Accel_Std_Dev_X",                    
"Time_Body_Accel_Std_Dev_Y","Time_Body_Accel_Std_Dev_Z",                    
"Time_Gravity_Accel_Mean_X","Time_Gravity_Accel_Mean_Y",
"Time_Gravity_Accel_Mean_Z","Time_Gravity_Accel_Std_Dev_X",                
"Time_Gravity_Accl_Std_Dev_Y","Time_Gravity_Accel_Std_Dev_Z",
"Time_Body_Accel_Jerk_Mean_X", "Time_Body_Accel_Jerk_Mean_Y",               
"Time_Body_Accel_Jerk_Mean_Z", "Time_Body_Accel_Jerk_Std_Dev_X",
"Time_Body_Accel_Jerk_Std_Dev_Y", "Time_Body_Accel_Jerk_Std_Dev_Z",
"Time_Body_Gyro_Mean_X", "Time_Body_Gyro_Mean_Y",
"Time_Body_Gyro_Mean_Z", "Time_Body_Gyro_Std_Dev_X",                   
"Time_Body_Gyro_Std_Dev_Y", "Time_Body_Gyro_Std_Dev_Z",
"Time_Body_Gyro_Jerk_Mean_X", "Time_Body_Gyro_Jerk_Mean_Y",
"Time_Body_Gyro_Jerk_Mean_Z", "Time_Body_Gyro_Jerk_Std_Dev_X",
"Time_Body_Gyro_Jerk_Std_Dev_Y","Time_Body_Gyro_Jerk_Std_Dev_Z",
"Time_Body_Accel_Mag_Mean", "Time_Body_Accel_Mag_Std_Dev",
"Time_Gravity_Accel_Mag_Mean", "Time_Gravity_Accel_Mag_Std_Dev",
"Time_Body_Accel_Jerk_Mag_Mean","Time_Body_Accel_Jerk_Mag_Std_Dev",
"Time_Body_Gyro_Mag_Mean","Time_Body_Gyro_Mag_Std_Dev",                 
"time_Body_Gyro_Jerk_Mean","Time_Body_Gyro_Jerk_Mag_Std_Dev",   
"angle(tBodyAccJerkMean),gravityMean)","angle(tBodyGyroMean,gravityMean)",    
"angle(tBodyGyroJerkMean,gravityMean)","Angle_X_Gravity_Mean",
"Angle_Y_Gravity_Mean","Angle_Z_Gravity_Mean",               
"type")